### ISSUE TITLE
想确认下acrobat001.20177是否不支持

### ISSUE THREAD

**Issue by henryyds** [QiuChenlyOpenSource/MyMacsAppCrack#38]
我知道文件中没说支持20177但是想自己试下
目前无效，不确定是否我的步骤出现了问题还是新版不支持。

**Comment by KangShanshuo** [comment]
这个补丁是会判断版本的，版本不对就啥都不会干

**Comment by henryyds** [comment]
> 这个补丁是会判断版本的，版本不对就啥都不会干

也就是如果说低于网站写的版本，百分百不会成功吗

**Comment by QiuChenly** [comment]
acrobat破解补丁存在问题，等后期后心情再修正 bug

**Comment by henryyds** [comment]
> acrobat破解补丁存在问题，等后期后心情再修正 bug

好的谢谢

**Comment by QiuChenly** [comment]
Issues resolved，pls read it
https://github.com/QiuChenlyOpenSource/InjectLib/commit/67ffbc20491bf1971cbaf87b74079b8d8870c763
