### ISSUE TITLE
Surge Enterprise 破解后还是显示试用已过期

### ISSUE THREAD

**Issue by DanielZWX** [QiuChenlyOpenSource/MyMacsAppCrack#52]
我之前下载过surge 5试用已过了期限，然后卸载了。
今天下载了readme链接中的版本（https://dl.nssurge.com/mac/v5/Surge-5.1.1-2251-25b569303a5219ac59c8375ba3cd1034.zip），不过与readme注释的v5.1.1 (2264)还是有点区别。

安装后，按文档说明的过程破解，然后运行，还是提示试用已过期。

不知是不是以下两个问题，还是其它原因
1）版本不对。但在surge官网无法找到v5.1.1 (2264)下载的位置，只有一个V5最新版提供试用下载。
2）之前试用已过期了，所以破解出问题。

**Comment by QiuChenly** [comment]
“一定要打开测试版本更新到我指定的最新版本！”这句话看不到吗？
我标的2264你看看你用的什么版本

**Comment by DanielZWX** [comment]
谢谢，下了这个匹配的版本就成功了。
之前因为试用过期了，所以确实不能进主界面下载匹配的版本，官网也找不到。
