### ISSUE TITLE
photoshop beta generative fill 能用吗？

### ISSUE THREAD

**Issue by guocity** [QiuChenlyOpenSource/MyMacsAppCrack#53]
photoshop beta generative fill 能用吗？

**Comment by QiuChenly** [comment]
目前上传的补丁不可用创作生成，但是此功能已经在本地测试代码中，很快将可用。

**Comment by guocity** [comment]
可以用的时候说一下，我发现ccdl.command 不工作了，现在怎么下载adobe 的package？

**Comment by guocity** [comment]
Photoshop 24.5.0 可以用，但是neural filter 不可以用

**Comment by QiuChenly** [comment]
neural filter是因为24.5这版本官方还没支持 所以用不了

**Comment by QiuChenly** [comment]
请关注另一个库，支持Adobe PS Beta 24.7并且支持创意填充。
https://github.com/QiuChenlyOpenSource/InjectLib/commit/ec640b04fd2d05bf1ec5d40c38eaba8a1dcba178
