### ISSUE TITLE
acrobat 23.003.20201 能破吗？

### ISSUE THREAD

**Issue by guocity** [QiuChenlyOpenSource/MyMacsAppCrack#54]
刚下了个 acrobat 是 版本 23.003.20201 能破吗？
或者教教，找什么，一起来破？

**Comment by guocity** [comment]
好像不可以，上面写trial expired

**Comment by QiuChenly** [comment]
下载地址在哪里

**Comment by QiuChenly** [comment]
Issues Resolved。
Pls read it：https://github.com/QiuChenlyOpenSource/InjectLib/commit/67ffbc20491bf1971cbaf87b74079b8d8870c763
