### ISSUE TITLE
CleanMyMac 破解后意外退出

### ISSUE THREAD

**Issue by Tianket** [QiuChenlyOpenSource/MyMacsAppCrack#61]
SIP已关闭

下面为崩溃报告
Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/Announcements.framework/Versions/A/Announcements
Referenced from: <F5148EDD-DBE6-3ED7-B7C5-7037CC6623C2> /Applications/CleanMyMac X.app/Contents/MacOS/CleanMyMac X
Reason: tried: '/usr/lib/swift/Announcements.framework/Versions/A/Announcements' (no such file, not in dyld cache), '/System/Volumes/Preboot/Cryptexes/OS/usr/lib/swift/Announcements.framework/Versions/A/Announcements' (no such file), '/Applications/CleanMyMac X.app/Contents/MacOS/../Frameworks/Announcements.framework/Versions/A/Announcements' (code signature in <61EBF1BF-CAD6-3FC8-BA1D-3E6A3C8C44BD> '/Applications/CleanMyMac X.app/Contents/Frameworks/Announcements.framework/Versions/A/Announcements' not valid for use in process: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed.), '/Applications/CleanMyMac X.app/Contents/Frameworks/Announcements.framework/Versions/A/Announcements' (code signature in <61EBF1BF-CAD6-3FC8-BA1D-3E6A3C8C44BD> '/Applications/CleanMyMac X.app/Contents/Fra
(terminated at launch; ignore backtrace)

**Comment by QiuChenly** [comment]
你把文件删了干什么
